apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argocd-helm-chart.fullname" .}}-ui
# namespace: {{ .Values.namespace }}
data:
  index.html: |
    <h1>Hello from Suraj!</h1>
    <p>This is my custom UI served by nginx.</p>
