apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name  }}
spec:
  replicas: {{ .Valaues.replicaCount }}
  selector:
    metaLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80