apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd-helm-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "argocd-helm-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "argocd-helm-chart.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: ui-html
              mountPath: /usr/share/nginx/html
          resources: {{- toYaml .Values.resources | nindent 12  }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
    volumes:
      - name: ui-html
        configMap:
          name: {{ include "argocd-helm-chart.fullname" .}}-ui