apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "argocd-helm-chart.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path  }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "argocd-helm-chart.name" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret }}